### PR TITLE
Website Update

### PR DESCRIPTION
**Pull request by chrisvogt**
This is in reference to #5.

#### See It In Action
Live at [http://chrisvogt.github.io/FriendsOfCake.github.io/](http://chrisvogt.github.io/FriendsOfCake.github.io/); or, [view the source](https://github.com/chrisvogt/FriendsOfCake.github.io).

~~Paragraphs of words deleted from here.~~

If you like how this is looking I can keeping giving it <span class="EmojiInput mj40" title="Heavy Black Heart ❤"></span> and will continue to submit pull requests.

##### Cleanup Notes
* I kept the `params.json` file around because I'm not familiar with it, and I noticed the line that asks not to remove the file.
* All front-end vendor packages (_styles_ & _js_) have been removed and are now managed by Bower. These are checked into the `components/` directory in the master branch, but are not in the `dev` branch.
* The logo files have been removed since they are not specific to this project. _Is there someplace more appropriate these could be moved to? Perhaps an official assets repository?_
* The `presentations/cakefest-2013` directory has been moved. (_Is there someplace more appropriate this could be moved to? Contains this [CakeFest 2013 Keynote](http://friendsofcake.com/presentations/cakefest-2013/keynote/), [Scaling CakePHP](http://friendsofcake.com/presentations/cakefest-2013/scaling-cakephp/), and this [Friends Of Cake presentation](http://friendsofcake.com/presentations/cakefest-2013/friends-of-cake/)_)

#### Screenshot
friendsofcake.com screenshotr/88J6bV5.gif)

### CODE REVIEW

**Comment by chrisvogt** [comment]
Just added some commits that make the additional documents more friendly as website pages. The changes can be reviewed live: [migration guide](http://chrisvogt.github.io/FriendsOfCake.github.io/migrations.html) and [boarding requirements](http://chrisvogt.github.io/FriendsOfCake.github.io/requirements.html).

**Comment by chrisvogt** [comment]
@jippi I see that the `presentations/cakefest-2013` directory (see above) was added by you. Will anything break if this directory is removed or migrated away from the repository?

**Comment by jadb** [comment]
I like where this is going. Not a big fan of the gray-gradient panels nor rounded corners but in general MUCH better than what's there now. Good job! :clap: 

But please, no gitter. We all hangout in #friendsofcake on Freenode, no need for gitter. What are others' opinion on that?

**Comment by ADmad** [comment]
> But please, no gitter. We all hangout in #friendsofcake on Freenode, no need for gitter.
Agreed

**Comment by dakota** [comment]
Agreed on both not having gitter and the gradient panels. I think the overall design is fantastic, but feel that the gradients and rounded corners cheapen it a bit. Perhaps something closer to the new CakePHP website?

**Comment by chrisvogt** [comment]
Unless someone submits something before then, I'll play around with it some more this evening and head more in the direction of [cakephp.org](cakephp.org) (flat, nice and sharp).

**Comment by chrisvogt** [comment]
Updated the [Pages](http://chrisvogt.github.io/FriendsOfCake.github.io/) demo. Doing this in chrisvogt/feature/style-flat. (I have yet to free the project boxes from the oppression of their cheap gradients.)

**Comment by jadb** [comment]
Getting better - I suck at design or would have helped :(

**Comment by chrisvogt** [comment]
No complaints from me @jadb, I enjoy working on the front end. Check out [how it's looking](http://chrisvogt.github.io/FriendsOfCake.github.io/) and/or the [source](https://github.com/chrisvogt/FriendsOfCake.github.io/tree/feature/style-flat). (I still need to tighten up the project overview boxes on desktop screen sizes.)

I would certainly appreciate recommendations for our options on retrieving and caching project metadata from the [GitHub API](https://developer.github.com/v3/repos/#get) using Jekyll/GitHub Pages. The hard-coded project data has already been moved into a[ datafile](https://github.com/chrisvogt/FriendsOfCake.github.io/blob/feature/style-flat/_data/projects.yml). See [this preview](http://bootsnipp.com/snippets/featured/minimal-preview-thumbnails) of the Bootsnipp element I'm using for the project boxes and pay attention to the metadata pane (could show stars, forks, etc.).

**Comment by jadb** [comment]
:+1: 

/cc @lorenzo @jippi

**Comment by dereuromark** [comment]
Yeah get this merged and deployed, guys! :)

**Comment by jippi** [comment]
Its now live :) 

http://friendsofcake.com/

the site is automatically rebuild every 30min when PRs are merged in

Thanks for the contribution @chrisvogt

**Comment by ADmad** [comment]
Great work @chrisvogt :clap:

**Pull request merged**
